### ISSUE TITLE
Unknown Content Type & UnicodeDecodeError

### ISSUE THREAD

**Issue by TaihouKai** [jessepav/boxtools#1]
I got the following 2 errors while running `boxnote2txt.py`:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 8679: character maps to <undefined>
```
(My BoxNote is in English, without weird characters)
I added `errors="replace"` to line 117 & 129 of `boxnote2txt.py` to solve this, and then I got another error:

```
Unknown content type: 'table'
Unknown content type: 'table'
Unknown content type: 'check_list'
Unknown content type: 'check_list'
Unknown content type: 'check_list'
```

---

Update:

Regarding `UnicodeDecodeError`

I checked the output markdown file, and it seems like `UnicodeDecodeError` is caused by the fancy weird backquote, automatically formatted by MacOS:
```
“foo” 
    ^
```

Regarding `Unknown content type`

I checked the markdown file output, and all checkboxes & tables are lost.

**Comment by jessepav** [comment]
As for the encoding issues, I've added two new options so you can specify the input and output encoding for your JSON and text/markdown files. It also displays your system default encoding, so you get an idea of what it tried to do by default.

As for tables and checklists, I only implemented the content types that I use in my own Box Notes, which are:

```
doc
paragraph
list_item
text
strong
em
hard_break
code_block
heading
horizontal_rule
blockquote
```

Check lists were straightforward, so I went ahead and just added support (type `check_list`), but tables are more complicated (they have rowspans and column spans and column widths), so those I'm going to leave alone for now, though I'd be happy to merge a PR for support.

**Comment by jessepav** [comment]
I went ahead and included basic support for tables: they're not rendered prettily, but rather as HTML (using `<table>`, `<tr>`, and `<td>`)
